apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshort-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshort-backend
  template:
    metadata:
      labels:
        app: urlshort-backend
    spec:
      containers:
        - name: backend
          image: elmimoha15/urlshort-backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: urlshort-backend
spec:
  selector:
    app: urlshort-backend
  ports:
    - name: http
      port: 8000         
      targetPort: 8000   
      nodePort: 30081    
  type: NodePort
