apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshort-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshort-frontend
  template:
    metadata:
      labels:
        app: urlshort-frontend
    spec:
      containers:
        - name: frontend
          image: elmimoha15/urlshort-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: urlshort-frontend
spec:
  selector:
    app: urlshort-frontend
  ports:
    - name: http
      port: 3000         
      targetPort: 3000   
      nodePort: 30080    
  type: NodePort
