name: CI/CD to MicroK8s

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build & Push Backend
      run: |
        docker build -t $DOCKER_USER/urlshort-backend:latest ./backend
        docker push $DOCKER_USER/urlshort-backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -t $DOCKER_USER/urlshort-frontend:latest ./frontend
        docker push $DOCKER_USER/urlshort-frontend:latest

    - name: Deploy to MicroK8s via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/url-shortener
          git pull
          microk8s kubectl apply -f k8s/backend.yaml
          microk8s kubectl apply -f k8s/frontend.yaml
